# k8s-manifests/headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-stateful-app
spec:
  clusterIP: None
  selector:
    app: my-stateful-app
  ports:
    - port: 80
      targetPort: 8080
